joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Cutter velocity controller (rad/s)
cutter_controller:
  type: velocity_controllers/JointVelocityController
  joint: cutter_joint
